name: Generate build

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
  schedule:
    - cron: '0 1 * * *'

jobs:
  build-and-upload:
    name: Build and upload
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl

          - build: windows-gnu
            os: windows-latest
            target: x86_64-pc-windows-gnu
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Install python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' 
      - name: Install requirements
        run: | 
          pip install -r requirements.txt
          pip install nuitka zstandard orderedset
          python3 -m nuitka --onefile zircolite.py
